### ISSUE TITLE
Claude 3 Support

### ISSUE THREAD

**Issue by ghost** [teralomaniac/Claude-auto-test#1]
Tried:
`model: 'claude-3-opus-20240229',`
`model: 'claude-3-sonnet-20240229',`
`model: 'claude-3,`
then
Res:
`Res:{"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-sonnet-20240229\" is not supported on this API. Please use the Messages API instead."}}`

**Comment by teralomaniac** [comment]
Resolved
